const langs=['ru','uz-lat','uz-cyr','en'];
const i18n={
ru:{brandSub:'Lab 5 · рефлексивно-регулятивный кейс',labBadge:'LAB 5 / CASE 01',eyebrow:'ИНТЕРАКТИВНАЯ РЕФЛЕКСИВНАЯ СИТУАЦИЯ',heroTitle:'Не просто оцени результат — <em>измени следующее действие.</em>',heroText:'В этом кейсе нужно сравнить ожидаемый и реальный результат, определить причины трудностей, использовать обратную связь, выбрать альтернативную стратегию и сформулировать следующую профессиональную цель.',steps:['Сравни','Определи','Проверь','Измени','Спланируй'],kicker:'2 КЛАСС · ГРУППОВОЕ ЗАДАНИЕ',sceneTitle:'Результат урока оказался слабее ожидаемого',time:'10–12 минут',boardLabel:'ОЖИДАЛОСЬ',boardTitle:'Большинство детей включится в работу',boardSub:'Каждая группа должна выполнить задание и объяснить свой результат.',expectedLabel:'Ожидаемый результат',expectedSub:'План урока',expectedQuote:'Группы распределят роли, выполнят задание и представят результат.',actualLabel:'Реальный результат',actualSub:'Наблюдение',actualQuote:'Часть детей почти не участвовала, роли были распределены неравномерно.',feedbackLabel:'Обратная связь',feedbackSub:'После задания',feedbackQuote:'Студенты группы сказали: «Мы не поняли, кто за что отвечает».',teacherName:'Вы — учитель',teacherNote:'Нужно превратить анализ результата в изменение следующего действия',knownTitle:'Что уже известно?',known:['Ожидаемый и реальный результаты различаются.','Есть наблюдение о распределении ролей и участии детей.','Есть обратная связь от участников ситуации.'],unknownLabel:'Пока нельзя утверждать:',unknownText:'что причина трудности только в мотивации детей или только в качестве задания.',
sec1:'01 / 05',s1Title:'Сравни ожидаемый и реальный результат',s1Text:'Выбери действие, которое лучше всего помогает зафиксировать расхождение, не объясняя причину заранее.',reason1Label:'Что именно различается?',reason1Placeholder:'Опиши наблюдаемое различие между планом и фактическим результатом...',to2:'Перейти к анализу причины →',
sec2:'02 / 05',s2Title:'Определи, что требует проверки',s2Text:'Не превращай первое предположение в окончательный вывод. Выбери, что нужно проверить дальше.',reason2Label:'Почему это нужно проверить?',reason2Placeholder:'Укажи, какое предположение ты проверяешь и на каком основании...',to3:'Перейти к обратной связи →',
sec3:'03 / 05',s3Title:'Используй обратную связь',s3Text:'Выбери способ использовать мнение участников как материал для корректировки следующего действия.',reason3Label:'Что ты узнал из обратной связи?',reason3Placeholder:'Свяжи обратную связь с конкретной трудностью ситуации...',to4:'Перейти к новой стратегии →',
sec4:'04 / 05',s4Title:'Выбери альтернативную стратегию',s4Text:'Теперь нужно изменить следующий ход, а не просто описать ошибку.',reason4Label:'Что именно изменишь?',reason4Placeholder:'Опиши новую стратегию и почему она должна изменить ситуацию...',to5:'Перейти к профессиональной цели →',
sec5:'05 / 05',s5Title:'Сформулируй следующую профессиональную цель',s5Text:'Цель должна быть связана с наблюдаемой трудностью и переноситься на новую педагогическую ситуацию.',reason5Label:'Какая цель станет следующей?',reason5Placeholder:'Сформулируй конкретное действие, которое ты попробуешь в следующей ситуации...',finish:'Завершить кейс →',
resultLabel:'ПРОФИЛЬ КЕЙСА',resultTitle:'Кейс завершён.',resultText:'Профиль отражает наблюдаемые рефлексивно-регулятивные действия в этом кейсе. Это не итоговый научный балл.',componentLabel:'компонента',methodStrong:'Методическая основа:',methodText:'Сравнение результата → выявление причины/затруднения → использование обратной связи → альтернативная стратегия → следующая профессиональная цель.',reset:'Пройти кейс заново',profileNames:{cognitive:'Когнитивный',social:'Социально-коммуникативный',digital:'Цифровая грамотность',reflective:'Рефлексивно-регулятивный'},evidenceLabels:{compare:'сопоставление ожидаемого и реального результата',cause:'выявление причины затруднения',feedback:'использование обратной связи',strategy:'альтернативная стратегия',goal:'следующая профессиональная цель'},indicators:{cognitive:['анализ педагогической ситуации','учёт возможных причин и последствий решения'],social:['использование позиции и обратной связи участников взаимодействия'],digital:['оценка результатов цифровой деятельности при необходимости'],reflective:['сравнение ожидаемых и реальных результатов','выявление причин успехов и трудностей','использование обратной связи','разработка альтернативной стратегии','постановка следующих профессиональных целей','перенос прежнего опыта в новую ситуацию с изменениями']}},
'uz-lat':{},'uz-cyr':{},en:{}};
// Keep the scientific wording stable; only interface/case language changes.
i18n['uz-lat']={...i18n.ru,
brandSub:'Lab 5 · refleksiv-regulyativ keys',labBadge:'LAB 5 / CASE 01',eyebrow:'INTERAKTIV REFLEKSIV VAZIYAT',
heroTitle:'Natijani shunchaki baholamang — <em>keyingi harakatni o‘zgartiring.</em>',
heroText:'Bu keysda kutilgan va real natijani solishtirish, qiyinchilik sabablarini aniqlash, teskari aloqadan foydalanish, alternativ strategiyani tanlash va keyingi kasbiy maqsadni belgilash kerak.',
steps:['Solishtiring','Aniqlang','Tekshiring','O‘zgartiring','Rejalashtiring'],
kicker:'2-SINF · GURUHLI TOPSHIRIQ',sceneTitle:'Dars natijasi kutilganidan pastroq bo‘ldi',time:'10–12 daqiqa',
boardLabel:'KUTILGAN EDI',boardTitle:'Bolalarning aksariyati ishga jalb etiladi',boardSub:'Har bir guruh vazifani bajarishi va o‘z natijasini tushuntirishi kerak.',
expectedLabel:'Kutilgan natija',expectedSub:'Dars rejasi',expectedQuote:'Guruhlar rollarni taqsimlaydi, vazifani bajaradi va natijasini taqdim etadi.',
actualLabel:'Real natija',actualSub:'Kuzatuv',actualQuote:'Ayrim bolalar deyarli qatnashmadi, rollar teng taqsimlanmadi.',
feedbackLabel:'Teskari aloqa',feedbackSub:'Topshiriqdan so‘ng',feedbackQuote:'Guruh talabalari aytdi: «Kim nima uchun javob berishini tushunmadik».',
teacherName:'Siz — o‘qituvchi',teacherNote:'Natija tahlilini keyingi harakatni o‘zgartirishga aylantirish kerak',
knownTitle:'Nima ma’lum?',known:['Kutilgan va real natijalar farq qiladi.','Rollar taqsimoti va bolalarning ishtiroki haqida kuzatuv mavjud.','Vaziyat ishtirokchilaridan teskari aloqa mavjud.'],
unknownLabel:'Hozircha xulosa qilib bo‘lmaydi:',unknownText:'qiyinchilik sababi faqat bolalarning motivatsiyasi yoki faqat topshiriq sifati ekanini.',
sec1:'01 / 05',s1Title:'Kutilgan va real natijani solishtiring',s1Text:'Sababni oldindan belgilamasdan, farqni aniqlashga yordam beradigan harakatni tanlang.',
reason1Label:'Nima farq qilmoqda?',reason1Placeholder:'Reja va haqiqiy natija o‘rtasidagi kuzatiladigan farqni yozing...',to2:'Sababni tahlil qilishga o‘tish →',
sec2:'02 / 05',s2Title:'Nimani tekshirish kerakligini aniqlang',s2Text:'Birinchi taxminni yakuniy xulosaga aylantirmang. Keyin nimani tekshirish kerakligini tanlang.',
reason2Label:'Nega buni tekshirish kerak?',reason2Placeholder:'Qaysi taxminni va nima asosida tekshirayotganingizni yozing...',to3:'Teskari aloqaga o‘tish →',
sec3:'03 / 05',s3Title:'Teskari aloqadan foydalaning',s3Text:'Ishtirokchilarning fikrini keyingi harakatni tuzatish uchun material sifatida ishlating.',
reason3Label:'Teskari aloqadan nimani bildingiz?',reason3Placeholder:'Teskari aloqani vaziyatdagi aniq qiyinchilik bilan bog‘lang...',to4:'Yangi strategiyaga o‘tish →',
sec4:'04 / 05',s4Title:'Alternativ strategiyani tanlang',s4Text:'Endi xatoni shunchaki tasvirlash emas, keyingi harakatni o‘zgartirish kerak.',
reason4Label:'Nimani o‘zgartirasiz?',reason4Placeholder:'Yangi strategiyani va nega u vaziyatni o‘zgartirishi mumkinligini yozing...',to5:'Kasbiy maqsadga o‘tish →',
sec5:'05 / 05',s5Title:'Keyingi kasbiy maqsadni belgilang',s5Text:'Maqsad kuzatilgan qiyinchilik bilan bog‘liq bo‘lsin va yangi pedagogik vaziyatga ko‘chirilishi mumkin bo‘lsin.',
reason5Label:'Keyingi maqsad nima?',reason5Placeholder:'Keyingi vaziyatda sinab ko‘radigan aniq harakatni yozing...',finish:'Keysni yakunlash →',
resultLabel:'KEYS PROFILI',resultTitle:'Keys yakunlandi.',resultText:'Profil ushbu keysdagi kuzatiladigan refleksiv-regulyativ harakatlarni ko‘rsatadi. Bu yakuniy ilmiy ball emas.',componentLabel:'komponent',
methodStrong:'Metodik asos:',methodText:'Natijani solishtirish → qiyinchilikni aniqlash → teskari aloqadan foydalanish → alternativ strategiya → keyingi kasbiy maqsad.',reset:'Keysni qayta o‘tish',
profileNames:{cognitive:'Kognitiv',social:'Ijtimoiy-kommunikativ',digital:'Raqamli savodxonlik',reflective:'Refleksiv-regulyativ'},
evidenceLabels:{compare:'kutilgan va real natijani solishtirish',cause:'qiyinchilik sababini aniqlash',feedback:'teskari aloqadan foydalanish',strategy:'alternativ strategiya',goal:'keyingi kasbiy maqsad'},
indicators:{cognitive:['pedagogik vaziyatni tahlil qilish','qarorning ehtimoliy sabablari va oqibatlarini hisobga olish'],social:['o‘zaro munosabat ishtirokchilarining pozitsiyasi va teskari aloqasidan foydalanish'],digital:['zarurat tug‘ilganda raqamli faoliyat natijalarini baholash'],reflective:['kutilgan va real natijalarni solishtirish','muvaffaqiyat va qiyinchiliklar sabablarini aniqlash','teskari aloqadan foydalanish','alternativ strategiya ishlab chiqish','keyingi kasbiy maqsadlarni belgilash','avvalgi tajribani yangi vaziyatga o‘zgartirib ko‘chirish']}};

i18n['uz-cyr']={...i18n.ru,
brandSub:'5-лаборатория · рефлексив-регулятив кейс',labBadge:'ЛАБ 5 / КЕЙС 01',eyebrow:'ИНТЕРАКТИВ РЕФЛЕКСИВ ВАЗИЯТ',
heroTitle:'Натижани шунчаки баҳоламанг — <em>кейинги ҳаракатни ўзгартиринг.</em>',
heroText:'Бу кейсда кутилган ва реал натижани солиштириш, қийинчилик сабабларини аниқлаш, тескари алоқадан фойдаланиш, альтернатив стратегияни танлаш ва кейинги касбий мақсадни белгилаш керак.',
steps:['Солиштиринг','Аниқланг','Текширинг','Ўзгартиринг','Режалаштиринг'],
kicker:'2-СИНФ · ГУРУҲЛИ ТОПШИРИҚ',sceneTitle:'Дарс натижаси кутилганидан пастроқ бўлди',time:'10–12 дақиқа',
boardLabel:'КУТИЛГАН ЭДИ',boardTitle:'Болаларнинг аксарияти ишга жалб этилади',boardSub:'Ҳар бир гуруҳ вазифани бажариши ва ўз натижасини тушунтириши керак.',
expectedLabel:'Кутилган натижа',expectedSub:'Дарс режаси',expectedQuote:'Гуруҳлар ролларни тақсимлайди, вазифани бажаради ва натижасини тақдим этади.',
actualLabel:'Реал натижа',actualSub:'Кузатув',actualQuote:'Айрим болалар деярли қатнашмади, роллар тенг тақсимланмади.',
feedbackLabel:'Тескари алоқа',feedbackSub:'Топшириқдан сўнг',feedbackQuote:'Гуруҳ талабалари айтди: «Ким нима учун жавоб беришини тушунмадик».',
teacherName:'Сиз — ўқитувчи',teacherNote:'Натижа таҳлилини кейинги ҳаракатни ўзгартиришга айлантириш керак',
knownTitle:'Нима маълум?',known:['Кутилган ва реал натижалар фарқ қилади.','Роллар тақсимоти ва болаларнинг иштироки ҳақида кузатув мавжуд.','Вазият иштирокчиларидан тескари алоқа мавжуд.'],
unknownLabel:'Ҳозирча хулоса қилиб бўлмайди:',unknownText:'қийинчилик сабаби фақат болаларнинг мотивацияси ёки фақат топшириқ сифати эканини.',
sec1:'01 / 05',s1Title:'Кутилган ва реал натижани солиштиринг',s1Text:'Сабабни олдиндан белгиламасдан, фарқни аниқлашга ёрдам берадиган ҳаракатни танланг.',
reason1Label:'Нима фарқ қилмоқда?',reason1Placeholder:'Режа ва ҳақиқий натижа ўртасидаги кузатиладиган фарқни ёзинг...',to2:'Сабабни таҳлил қилишга ўтиш →',
sec2:'02 / 05',s2Title:'Нимани текшириш кераклигини аниқланг',s2Text:'Биринчи тахминни якуний хулосага айлантирманг. Кейин нимани текшириш кераклигини танланг.',
reason2Label:'Нега буни текшириш керак?',reason2Placeholder:'Қайси тахминни ва нима асосида текшираётганингизни ёзинг...',to3:'Тескари алоқага ўтиш →',
sec3:'03 / 05',s3Title:'Тескари алоқадан фойдаланинг',s3Text:'Иштирокчиларнинг фикрини кейинги ҳаракатни тузатиш учун материал сифатида ишлатинг.',
reason3Label:'Тескари алоқадан нимани билдингиз?',reason3Placeholder:'Тескари алоқани вазиятдаги аниқ қийинчилик билан боғланг...',to4:'Янги стратегияга ўтиш →',
sec4:'04 / 05',s4Title:'Альтернатив стратегияни танланг',s4Text:'Энди хатони шунчаки тасвирлаш эмас, кейинги ҳаракатни ўзгартириш керак.',
reason4Label:'Нимани ўзгартирасиз?',reason4Placeholder:'Янги стратегияни ва нега у вазиятни ўзгартириши мумкинлигини ёзинг...',to5:'Касбий мақсадга ўтиш →',
sec5:'05 / 05',s5Title:'Кейинги касбий мақсадни белгиланг',s5Text:'Мақсад кузатилган қийинчилик билан боғлиқ бўлсин ва янги педагогик вазиятга кўчирилиши мумкин бўлсин.',
reason5Label:'Кейинги мақсад нима?',reason5Placeholder:'Кейинги вазиятда синаб кўрадиган аниқ ҳаракатни ёзинг...',finish:'Кейсни якунлаш →',
resultLabel:'КЕЙС ПРОФИЛИ',resultTitle:'Кейс якунланди.',resultText:'Профил ушбу кейсда кузатилган рефлексив-регулятив ҳаракатларни кўрсатади. Бу якуний илмий балл эмас.',componentLabel:'компонент',
methodStrong:'Методик асос:',methodText:'Натижани солиштириш → қийинчиликни аниқлаш → тескари алоқадан фойдаланиш → альтернатив стратегия → кейинги касбий мақсад.',reset:'Кейсни қайта ўтиш',
profileNames:{cognitive:'Когнитив',social:'Ижтимоий-коммуникатив',digital:'Рақамли саводхонлик',reflective:'Рефлексив-регулятив'},
evidenceLabels:{compare:'кутилган ва реал натижани солиштириш',cause:'қийинчилик сабабини аниқлаш',feedback:'тескари алоқадан фойдаланиш',strategy:'альтернатив стратегия',goal:'кейинги касбий мақсад'},
indicators:{cognitive:['педагогик вазиятни таҳлил қилиш','қарорнинг эҳтимолий сабаблари ва оқибатларини ҳисобга олиш'],social:['ўзаро муносабат иштирокчиларининг позицияси ва тескари алоқасидан фойдаланиш'],digital:['зарурат туғилганда рақамли фаолият натижаларини баҳолаш'],reflective:['кутилган ва реал натижаларни солиштириш','муваффақият ва қийинчиликлар сабабларини аниқлаш','тескари алоқадан фойдаланиш','альтернатив стратегия ишлаб чиқиш','кейинги касбий мақсадларни белгилаш','аввалги тажрибани янги вазиятга ўзгартириб кўчириш']}}
i18n.en={...i18n.ru,
brandSub:'Lab 5 · reflective-regulatory case',labBadge:'LAB 5 / CASE 01',eyebrow:'INTERACTIVE REFLECTIVE SITUATION',
heroTitle:'Do not only assess the result — <em>change the next action.</em>',
heroText:'Compare the expected and actual result, identify possible difficulties, use feedback, choose an alternative strategy and set a next professional goal.',
steps:['Compare','Identify','Check','Change','Plan'],kicker:'GRADE 2 · GROUP TASK',sceneTitle:'The lesson result was weaker than expected',time:'10–12 minutes',
boardLabel:'EXPECTED',boardTitle:'Most learners will engage in the task',boardSub:'Each group should complete the task and explain its result.',
expectedLabel:'Expected result',expectedSub:'Lesson plan',expectedQuote:'Groups will distribute roles, complete the task and present their result.',
actualLabel:'Actual result',actualSub:'Observation',actualQuote:'Some learners participated very little and roles were unevenly distributed.',
feedbackLabel:'Feedback',feedbackSub:'After the task',feedbackQuote:'Students said: “We did not understand who was responsible for what.”',
teacherName:'You are the teacher',teacherNote:'Turn analysis of the result into a change in the next action',
knownTitle:'What is already known?',known:['Expected and actual results differ.','There is observation about role distribution and learner participation.','There is feedback from participants.'],
unknownLabel:'It cannot yet be concluded:',unknownText:'that the difficulty is caused only by learner motivation or only by task quality.',
sec1:'01 / 05',s1Title:'Compare the expected and actual result',s1Text:'Choose the action that helps record the gap without deciding the cause in advance.',reason1Label:'What exactly is different?',reason1Placeholder:'Describe the observable difference between the plan and the actual result...',to2:'Move to cause analysis →',
sec2:'02 / 05',s2Title:'Identify what needs checking',s2Text:'Do not turn the first assumption into a final conclusion. Choose what should be checked next.',reason2Label:'Why should this be checked?',reason2Placeholder:'State which assumption you are checking and on what basis...',to3:'Move to feedback →',
sec3:'03 / 05',s3Title:'Use feedback',s3Text:'Use participants’ feedback as evidence for adjusting the next action.',reason3Label:'What did you learn from the feedback?',reason3Placeholder:'Connect the feedback to a concrete difficulty in the situation...',to4:'Move to a new strategy →',
sec4:'04 / 05',s4Title:'Choose an alternative strategy',s4Text:'Now change the next move rather than only describing the mistake.',reason4Label:'What will you change?',reason4Placeholder:'Describe the new strategy and why it may change the situation...',to5:'Move to a professional goal →',
sec5:'05 / 05',s5Title:'Set the next professional goal',s5Text:'The goal should relate to the observed difficulty and transfer to a new pedagogical situation.',reason5Label:'What is the next goal?',reason5Placeholder:'Write the concrete action you will try in the next situation...',finish:'Finish the case →',
resultLabel:'CASE PROFILE',resultTitle:'Case completed.',resultText:'The profile shows observable reflective-regulatory actions in this case. It is not a final scientific score.',componentLabel:'component',
methodStrong:'Methodological basis:',methodText:'Compare result → identify difficulty → use feedback → alternative strategy → next professional goal.',reset:'Restart case',
profileNames:{cognitive:'Cognitive',social:'Social-communicative',digital:'Digital literacy',reflective:'Reflective-regulatory'},
evidenceLabels:{compare:'comparison of expected and actual result',cause:'identification of difficulty cause',feedback:'use of feedback',strategy:'alternative strategy',goal:'next professional goal'},
indicators:{cognitive:['analysis of the pedagogical situation','consideration of possible causes and consequences of the decision'],social:['use of participants’ positions and feedback in interaction'],digital:['evaluation of digital activity results when relevant'],reflective:['comparison of expected and actual results','identification of causes of success and difficulty','use of feedback','development of an alternative strategy','setting next professional goals','transfer of previous experience to a new situation with adaptations']}};


const choices={
1:[{id:1,title:{ru:'Сразу объяснить, почему дети были недостаточно мотивированы',"uz-lat":'Darhol bolalar nega yetarlicha motivatsiyaga ega bo‘lmaganini tushuntirish','uz-cyr':'Дарҳол болалар нима учун етарлича мотивацияга эга бўлмаганини тушунтириш',en:'Immediately explain why the learners were not motivated'},text:{ru:'Это уже объяснение причины, а не фиксация различия.',"uz-lat":'Bu farqni aniqlash emas, sababni oldindan tushuntirishdir.','uz-cyr':'Бу фарқни аниқлаш эмас, сабабни олдиндан тушунтиришдир.',en:'This is already an explanation of the cause, not a record of the difference.'}},{id:2,title:{ru:'Сопоставить план и фактическое наблюдение',"uz-lat":'Reja va amaldagi kuzatuvni solishtirish','uz-cyr':'Режа ва амалдаги кузатувни солиштириш',en:'Compare the plan with the actual observation'},text:{ru:'Так можно зафиксировать, где именно ожидаемый результат не совпал с реальным.',"uz-lat":'Shu orqali kutilgan natija qayerda real natijadan farq qilganini aniqlash mumkin.','uz-cyr':'Шу орқали кутилган натижа қаерда реал натижадан фарқ қилганини аниқлаш мумкин.',en:'This identifies exactly where the expected result differed from the actual one.'}},{id:3,title:{ru:'Сразу изменить весь сценарий урока',"uz-lat":'Dars ssenariysini darhol to‘liq o‘zgartirish','uz-cyr':'Дарс сценарийсини дарҳол тўлиқ ўзгартириш',en:'Immediately redesign the whole lesson'},text:{ru:'Изменение без анализа результата не показывает, что именно нужно исправить.',"uz-lat":'Natijani tahlil qilmasdan o‘zgartirish nimani tuzatish kerakligini ko‘rsatmaydi.','uz-cyr':'Натижани таҳлил қилмасдан ўзгартириш нимани тузатиш кераклигини кўрсатмайди.',en:'Changing everything without analyzing the result does not show what needs improvement.'}}],
2:[{id:1,title:{ru:'Предположить, что причина только в мотивации детей',"uz-lat":'Sabab faqat bolalarning motivatsiyasida deb taxmin qilish','uz-cyr':'Сабаб фақат болаларнинг мотивациясида деб тахмин қилиш',en:'Assume the cause is only learner motivation'},text:{ru:'Это гипотеза, которую ещё нужно проверить.',"uz-lat":'Bu hali tekshirilishi kerak bo‘lgan farazdir.','uz-cyr':'Бу ҳали текширилиши керак бўлган фараздир.',en:'This is a hypothesis that still needs checking.'}},{id:2,title:{ru:'Проверить, как были сформулированы роли и инструкция',"uz-lat":'Rollar va ko‘rsatma qanday berilganini tekshirish','uz-cyr':'Роллар ва кўрсатма қандай берилганини текшириш',en:'Check how the roles and instructions were defined'},text:{ru:'Обратная связь прямо указывает на возможную проблему распределения ответственности.',"uz-lat":'Teskari aloqa javobgarlikni taqsimlashda muammo bo‘lishi mumkinligini ko‘rsatadi.','uz-cyr':'Тескари алоқа жавобгарликни тақсимлашда муаммо бўлиши мумкинлигини кўрсатади.',en:'The feedback points to a possible issue with responsibility distribution.'}},{id:3,title:{ru:'Принять первое предположение как окончательную причину',"uz-lat":'Birinchi taxminni yakuniy sabab deb qabul qilish','uz-cyr':'Биринчи тахминни якуний сабаб деб қабул қилиш',en:'Treat the first assumption as the final cause'},text:{ru:'Это не оставляет места для проверки альтернативных объяснений.',"uz-lat":'Bu boshqa ehtimoliy tushuntirishlarni tekshirishga imkon bermaydi.','uz-cyr':'Бу бошқа эҳтимолий тушунтиришларни текширишга имкон бермайди.',en:'This leaves no room to check alternative explanations.'}}],
3:[{id:1,title:{ru:'Игнорировать обратную связь, чтобы сохранить первоначальный план',"uz-lat":'Dastlabki rejani saqlash uchun teskari aloqani e’tiborsiz qoldirish','uz-cyr':'Дастлабки режани сақлаш учун тескари алоқани эътиборсиз қолдириш',en:'Ignore the feedback to preserve the original plan'},text:{ru:'Обратная связь остаётся неиспользованным доказательством.',"uz-lat":'Teskari aloqa foydalanilmagan dalil bo‘lib qoladi.','uz-cyr':'Тескари алоқа фойдаланилмаган далил бўлиб қолади.',en:'The feedback remains unused evidence.'}},{id:2,title:{ru:'Связать обратную связь с конкретной трудностью',"uz-lat":'Teskari aloqani aniq qiyinchilik bilan bog‘lash','uz-cyr':'Тескари алоқани аниқ қийинчилик билан боғлаш',en:'Connect the feedback to a concrete difficulty'},text:{ru:'Так обратная связь превращается в материал для корректировки следующего действия.',"uz-lat":'Shunda teskari aloqa keyingi harakatni tuzatish uchun materialga aylanadi.','uz-cyr':'Шунда тескари алоқа кейинги ҳаракатни тузатиш учун материалга айланади.',en:'This turns feedback into evidence for adjusting the next action.'}},{id:3,title:{ru:'Выбрать только положительный отзыв',"uz-lat":'Faqat ijobiy fikrni tanlash','uz-cyr':'Фақат ижобий фикрни танлаш',en:'Use only positive feedback'},text:{ru:'Это ограничивает анализ и скрывает возможные трудности.',"uz-lat":'Bu tahlilni cheklaydi va ehtimoliy qiyinchiliklarni yashiradi.','uz-cyr':'Бу таҳлилни чеклайди ва эҳтимолий қийинчиликларни яширади.',en:'This limits the analysis and can hide difficulties.'}}],
4:[{id:1,title:{ru:'Повторить тот же сценарий без изменений',"uz-lat":'Xuddi shu ssenariyni o‘zgarishsiz takrorlash','uz-cyr':'Худди шу сценарийни ўзгаришсиз такрорлаш',en:'Repeat the same scenario without changes'},text:{ru:'Это не показывает, как рефлексия повлияла на следующее действие.',"uz-lat":'Bu refleksiya keyingi harakatni qanday o‘zgartirganini ko‘rsatmaydi.','uz-cyr':'Бу рефлексия кейинги ҳаракатни қандай ўзгартирганини кўрсатмайди.',en:'This does not show how reflection changed the next action.'}},{id:2,title:{ru:'Изменить инструкцию и заранее распределить роли',"uz-lat":'Ko‘rsatmani o‘zgartirish va rollarni oldindan taqsimlash','uz-cyr':'Кўрсатмани ўзгартириш ва ролларни олдиндан тақсимлаш',en:'Change the instructions and assign roles in advance'},text:{ru:'Изменение напрямую связано с выявленной трудностью и может быть проверено в следующей ситуации.',"uz-lat":'O‘zgarish aniqlangan qiyinchilik bilan bog‘liq va keyingi vaziyatda tekshirilishi mumkin.','uz-cyr':'Ўзгариш аниқланган қийинчилик билан боғлиқ ва кейинги вазиятда текширилиши мумкин.',en:'The change directly addresses the identified difficulty and can be checked next time.'}},{id:3,title:{ru:'Увеличить объём задания для повышения активности',"uz-lat":'Faollikni oshirish uchun topshiriq hajmini ko‘paytirish','uz-cyr':'Фаолликни ошириш учун топшириқ ҳажмини кўпайтириш',en:'Increase the amount of work to raise participation'},text:{ru:'Увеличение объёма само по себе не связано с выявленной проблемой ролей.',"uz-lat":'Topshiriq hajmini oshirish rollar bilan bog‘liq muammoni bevosita hal qilmaydi.','uz-cyr':'Топшириқ ҳажмини ошириш роллар билан боғлиқ муаммони бевосита ҳал қилмайди.',en:'More work does not directly address the identified role problem.'}}],
5:[{id:1,title:{ru:'Поставить общую цель «проводить уроки лучше»',"uz-lat":'«Darslarni yaxshiroq o‘tkazish» kabi umumiy maqsad qo‘yish','uz-cyr':'«Дарсларни яхшироқ ўтказиш» каби умумий мақсад қўйиш',en:'Set a general goal: “teach lessons better”'},text:{ru:'Такая формулировка не показывает конкретного следующего действия.',"uz-lat":'Bunday maqsad aniq keyingi harakatni ko‘rsatmaydi.','uz-cyr':'Бундай мақсад аниқ кейинги ҳаракатни кўрсатмайди.',en:'This wording does not show a concrete next action.'}},{id:2,title:{ru:'В следующей групповой работе заранее распределить роли и проверить, как дети поняли инструкцию',"uz-lat":'Keyingi guruh ishida rollarni oldindan taqsimlash va bolalar ko‘rsatmani qanday tushunganini tekshirish','uz-cyr':'Кейинги гуруҳ ишида ролларни олдиндан тақсимлаш ва болалар кўрсатмани қандай тушунганини текшириш',en:'In the next group task, assign roles in advance and check how learners understood the instructions'},text:{ru:'Цель конкретна, связана с выявленной трудностью и переносится на новую ситуацию.',"uz-lat":'Maqsad aniq, aniqlangan qiyinchilik bilan bog‘liq va yangi vaziyatga ko‘chiriladi.','uz-cyr':'Мақсад аниқ, аниқланган қийинчилик билан боғлиқ ва янги вазиятга кўчирилади.',en:'The goal is concrete, linked to the difficulty and transferable to a new situation.'}},{id:3,title:{ru:'Поставить цель ничего не менять, пока не появится новая проблема',"uz-lat":'Yangi muammo chiqmaguncha hech narsani o‘zgartirmaslik maqsadini qo‘yish','uz-cyr':'Янги муаммо чиқмагунча ҳеч нарсани ўзгартирмаслик мақсадини қўйиш',en:'Set a goal of changing nothing until a new problem appears'},text:{ru:'Такая цель не превращает рефлексию в осознанное изменение действия.',"uz-lat":'Bunday maqsad refleksiyani ongli harakat o‘zgarishiga aylantirmaydi.','uz-cyr':'Бундай мақсад рефлексияни онгли ҳаракат ўзгаришига айлантирмайди.',en:'This does not turn reflection into a deliberate change in action.'}}]
};
let lang=localStorage.getItem('tl_lang') || localStorage.getItem('tl-lab5-lang') || 'ru'; if(!langs.includes(lang)) lang='ru'; let picks={1:null,2:null,3:null,4:null,5:null};
const $=id=>document.getElementById(id), set=(id,v)=>{if($(id))$(id).innerHTML=v}, d=()=>i18n[lang];
function renderSteps(){const el=$('stepper');el.innerHTML=d().steps.map((x,i)=>`<div class="step ${i===0?'active':''}"><b>0${i+1}</b><span>${x}</span></div>${i<4?'<div class="line"></div>':''}`).join('')}
function setStep(n){document.querySelectorAll('.stepper .step').forEach((s,i)=>s.classList.toggle('active',i===n))}
function applyLanguage(){const x=d();document.documentElement.lang=lang==='ru'?'ru':lang==='en'?'en':'uz';renderSteps();Object.entries({brandSub:'brandSub',labBadge:'labBadge',eyebrow:'eyebrow',heroTitle:'heroTitle',heroText:'heroText',sceneKicker:'kicker',sceneTitle:'sceneTitle',timeChip:'time',boardLabel:'boardLabel',boardTitle:'boardTitle',boardSub:'boardSub',expectedLabel:'expectedLabel',expectedSub:'expectedSub',expectedQuote:'expectedQuote',actualLabel:'actualLabel',actualSub:'actualSub',actualQuote:'actualQuote',feedbackLabel:'feedbackLabel',feedbackSub:'feedbackSub',feedbackQuote:'feedbackQuote',teacherName:'teacherName',teacherNote:'teacherNote',knownTitle:'knownTitle',unknownLabel:'unknownLabel',unknownText:'unknownText',sec1:'sec1',s1Title:'s1Title',s1Text:'s1Text',reason1Label:'reason1Label',to2:'to2',sec2:'sec2',s2Title:'s2Title',s2Text:'s2Text',reason2Label:'reason2Label',to3:'to3',sec3:'sec3',s3Title:'s3Title',s3Text:'s3Text',reason3Label:'reason3Label',to4:'to4',sec4:'sec4',s4Title:'s4Title',s4Text:'s4Text',reason4Label:'reason4Label',to5:'to5',sec5:'sec5',s5Title:'s5Title',s5Text:'s5Text',reason5Label:'reason5Label',finishBtn:'finish',resultLabel:'resultLabel',resultTitle:'resultTitle',resultText:'resultText',componentLabel:'componentLabel',methodStrong:'methodStrong',methodText:'methodText',resetCase:'reset'}).forEach(([id,k])=>set(id,x[k]));[1,2,3,4,5].forEach(i=>$(
'reason'+i).placeholder=x['reason'+i+'Placeholder']);renderAll();update()}
function esc(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(n){const box=$('grid'+n);box.innerHTML='';choices[n].forEach(o=>{const b=document.createElement('button');b.className='decision'+(picks[n]?.id===o.id?' selected':'');b.innerHTML=`<div class="option-no">${lang==='ru'||lang==='uz-cyr'?'ВАРИАНТ':lang==='en'?'OPTION':'VARIANT'} 0${o.id}</div><h3>${o.title[lang]}</h3><p>${o.text[lang]}</p>`;b.onclick=()=>{picks[n]=o;render(n);$('reasonBox'+n).classList.remove('hidden');$('reason'+n).focus();update()};box.appendChild(b)})}
function evidence(){const e={cognitive:new Set(),social:new Set(),digital:new Set(),reflective:new Set()}; if(picks[1]?.id===2){e.reflective.add('compare');e.cognitive.add('compare')} if(picks[2]?.id===2){e.reflective.add('cause');e.cognitive.add('cause')} if(picks[3]?.id===2){e.reflective.add('feedback');e.social.add('feedback')} if(picks[4]?.id===2)e.reflective.add('strategy'); if(picks[5]?.id===2)e.reflective.add('goal'); return e}
function renderProfile(){const x=d(),e=evidence(),box=$('profileGrid');box.innerHTML='';Object.keys(x.profileNames).forEach(k=>{const labels=[...e[k]].map(v=>x.evidenceLabels[v]);const el=document.createElement('div');el.className='profile';el.innerHTML=`<div class="profile-name">${x.profileNames[k]}</div>${labels.length?`<div class="evidence-tags">${labels.map(esc).map(v=>`<span>${v}</span>`).join('')}</div>`:`<div class="muted">${lang==='ru'?'В этом кейсе мало наблюдаемых данных по компоненту.':lang==='en'?'This case provides limited observable evidence for this component.':lang==='uz-cyr'?'Бу кейсда ушбу компонент бўйича кузатиладиган далиллар кам.':'Bu keysda ushbu komponent bo‘yicha kuzatiladigan dalillar kam.'}</div>`}<details><summary>${lang==='ru'?'Связанные индикаторы':lang==='en'?'Related indicators':lang==='uz-cyr'?'Боғлиқ индикаторлар':'Bog‘liq indikatorlar'}</summary><ul>${x.indicators[k].map(esc).map(v=>`<li>${v}</li>`).join('')}</ul></details>`;box.appendChild(el)})}
function renderAll(){[1,2,3,4,5].forEach(render);renderProfile()}
function update(){for(let i=1;i<=5;i++)$('chars'+i).textContent=$('reason'+i).value.length;$('to2').disabled=!picks[1]||$('reason1').value.trim().length<20;$('to3').disabled=!picks[2]||$('reason2').value.trim().length<20;$('to4').disabled=!picks[3]||$('reason3').value.trim().length<20;$('to5').disabled=!picks[4]||$('reason4').value.trim().length<20;$('finishBtn').disabled=!picks[5]||$('reason5').value.trim().length<20}
function show(id,n){$(id).classList.remove('hidden');setStep(n);$(id).scrollIntoView({behavior:'smooth',block:'start'})}
for(let i=1;i<=5;i++)$('reason'+i).addEventListener('input',update);
$('to2').onclick=()=>{if(!$('to2').disabled)show('step2Card',1)};$('to3').onclick=()=>{if(!$('to3').disabled)show('step3Card',2)};$('to4').onclick=()=>{if(!$('to4').disabled)show('step4Card',3)};$('to5').onclick=()=>{if(!$('to5').disabled)show('step5Card',4)};
$('finishBtn').onclick=()=>{if($('finishBtn').disabled)return;renderProfile();localStorage.setItem('tl-lab5-case01',JSON.stringify({lang,picks:Object.fromEntries(Object.entries(picks).map(([k,v])=>[k,v?.id||null])),reasons:[1,2,3,4,5].map(i=>$('reason'+i).value.trim()),completedAt:new Date().toISOString()}));$('resultSection').classList.remove('hidden');setStep(4);$('resultSection').scrollIntoView({behavior:'smooth',block:'start'})};
$('languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('tl_lang',lang);localStorage.setItem('tl-lab5-lang',lang);applyLanguage()};
$('resetCase').onclick=()=>{picks={1:null,2:null,3:null,4:null,5:null};[2,3,4,5].forEach(i=>$('step'+i+'Card').classList.add('hidden'));$('resultSection').classList.add('hidden');[1,2,3,4,5].forEach(i=>{$('reason'+i).value='';$('reasonBox'+i).classList.add('hidden')});setStep(0);renderAll();update();window.scrollTo({top:0,behavior:'smooth'})};
$('languageSelect').value=lang; applyLanguage(); update();
